name: Release Org

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Release
        uses: railmapgen/releaser-org@main
        with:
          app_name: rmp
